### ISSUE TITLE
A little help for "neck" image

### ISSUE THREAD

**Issue by prp-e** [iamhimanshu0/face-filter#1]
Hello. Hope you're doing well. 
I looked at your code and it's perfectly written and matches my needs. But I need a little help.
First, you have a button and onClick system, which I don't want to happen. Second, I just want the user to open the browser and see the "neck" image around her neck. 
May you help me do that?

With best regards.

**Comment by iamhimanshu0** [comment]
Hi, it's really easy, all you need to do, remove all the other filter and just add your neck filter, i'm loading the filter on button click you can remove the functionality and add your own way, 
Hope this helps,
